spring:
  datasource:
    url: jdbc:mysql://localhost:3306/litecase?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    # 密码纯数字不需要加引号
    password: 123456
#    默认配置 hikari数据源
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      maximum-pool-size: 15
#      minimum-idle: 5
#      idle-timeout: 30000

server:
  port: 9000



