spring:
  datasource:
    url: jdbc:mysql://localhost:3306/litecase_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    # 密码纯数字不需要加引号
    password: 123456
  #    默认配置 hikari数据源
  #    type: com.zaxxer.hikari.HikariDataSource
  #    hikari:
  #      maximum-pool-size: 15
  #      minimum-idle: 5
  #      idle-timeout: 30000
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      # password: 123456
      jedis:
        pool:
          max-wait: 1ms # 连接池最大阻塞等待时间
          max-active: 8 # 最大连接数
          max-idle: 4 # 连接池中的最大空闲连接数
          min-idle: 0 # 连接池中的最小空闲连接数
      database: 0 # 操作的是0号数据库

  servlet:
    multipart:
      # 设置能接受的文件最大的大小，记得是MB,或KB, 默认大小为1MB
      max-file-size: 100KB
      # 设置一次上传的所有文件的大小, 默认10MB
      max-request-size: 30MB
  security:
    user:
      name: user
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml # 配置mybatis扫描mapper文件xml的路径


#  使用map-underscore-to-camel-case/db-column-underline在插入数据的时候将实体类的驼峰格式转成下划线格式
#  只要设置db-column-underline与map-underscore-to-camel-case任意一个参数为true，实体类的字段都会自动转下划线的格式.
mybatis-plus:
  global:
    db-column-underline: true
    configuration:
      map-underscore-to-camel-case: true

server:
  port: 9000
  tomcat:
    max-swallow-size: 100MB # 设置multipart的max-file-size或者max-request-size时，可能需要修改tomcat的吞吐量, 设置为-1, 表示不限制大小

# springdoc-openapi项目配置, 最后访问: http://localhost:9000/doc.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaominfo.knife4j.demo.web
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# minio 对象存储服务配置
S3:
  url: http://localhost:9000
  access-key: admin
  secret-key: 123456
  bucket-name: test

litecase:
  path: D://
